repo: avoid use datetime.UTC
Issue: LINCD-19009

datetime.UTC is an alias for the UTC timezone singleton
datetime.timezone.utc, which is added in python 3.11. On host with
python lower than 3.11, run command like " ./.repo/repo/repo start hello
layers/meta-*" will be failed with error:
AttributeError: module 'datetime' has no attribute 'UTC'

Replace datetime.UTC with datetime.timezone.utc for fixing above issue

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Chen Qi <Qi.Chen@windriver.com>