project.py: Set core.compression = 0
Issue: LIN1024-3021

The files in dl layers are binaries, compress them doesn't make any sense,
and may cost a lot of time for large files, which caused errors like:

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed

This is becuase the compression for large files cost a lot of time, and server
thinks that the client is lost and close the connection.

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>